# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161120_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_active',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_active',
            field=models.BooleanField(default=False),
        ),
    ]
